 const changeButton = document.getElementById('changeButton');
    const container = document.querySelector('.container');
    const header = document.getElementById('header');
    const content = document.getElementById('content');

    changeButton.addEventListener('click', () => {
      container.classList.toggle('dated');
      if (container.classList.contains('dated')) {
        header.textContent = 'Shin Godzilla';
        content.textContent = '"Shin Godzilla," released in 2016, revitalizes the iconic Godzilla franchise with a compelling narrative that combines thrilling action with thought-provoking themes. Directed by Hideaki Anno and Shinji Higuchi, the film offers a modern take on the classic kaiju genre, reimagining the titular monster as a symbol of nuclear devastation and societal reckoning. The story unfolds against the backdrop of contemporary Japan, where the sudden emergence of a monstrous creature in Tokyo Bay sends shockwaves through the nation. As the colossal creature, dubbed "Godzilla," unleashes its fury upon the city, government officials and military forces are thrust into a frantic scramble to contain the unprecedented threat. However, bureaucratic hurdles and political maneuvering impede effective response efforts, leaving the populace vulnerable to Godzillas relentless rampage. As the creature evolves and exhibits new, terrifying abilities, including the iconic atomic breath, the situation grows increasingly dire, with the fate of Japan hanging in the balance. Amidst the chaos, a diverse ensemble of characters emerges to confront the Godzilla crisis. From dedicated scientists and resourceful government officials to ordinary citizens caught in the crossfire, each individual grapples with their own fears, motivations, and moral dilemmas in the face of unimaginable catastrophe. As the narrative unfolds, "Shin Godzilla" delves deep into themes of disaster management, governmental accountability, and the human cost of unchecked ambition. Through its intricate plotting and nuanced character development, the film offers a sobering reflection on humanitys relationship with nature and the consequences of our actions. At its core, "Shin Godzilla" is a testament to the enduring relevance of the Godzilla mythos, transcending its origins as a mere monster movie to become a powerful allegory for contemporary society. With its breathtaking special effects, pulse-pounding action sequences, and poignant social commentary, the film stands as a landmark achievement in the pantheon of kaiju cinema, captivating audiences with its spectacle and substance alike.';
      } else {
        header.textContent = 'Godzilla Appreciation Page';
        content.textContent = 'Back in highschool I made a vector art image taking inspiration from a poster for the "Shin Godzilla" movie. I wanted to capture the feeling of that poster so I painstakingly traced every line, crevice, and tooth of Godzilla. I also added some burning city buildings at the bottom to showcase the destructive force that godzilla is. I put a lot of time and effort into this project. I was and still am thoroughly satisfied with the final product.';
      }
    });
